FROM debian

#Set env var so logging works
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get upgrade -y && \
 apt-get install python3 python3-pip -y && \
 pip3 install pandas && \
 pip3 install -i https://test.pypi.org/simple/ lambdataseancode && \
 python3 -c "import lambdataseancode"